import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function generateRandomName(): string {
  const adjectives = [
    "abundant",
    "agile",
    "ambitious",
    "bright",
    "brave",
    "calm",
    "clever",
    "creative",
    "curious",
    "daring",
    "dynamic",
    "eager",
    "energetic",
    "elegant",
    "enthusiastic",
    "fierce",
    "focused",
    "friendly",
    "funny",
    "generous",
    "graceful",
    "happy",
    "honest",
    "humble",
    "imaginative",
    "inspiring",
    "intelligent",
    "joyful",
    "kind",
    "lively",
    "motivated",
    "nimble",
    "optimistic",
    "outgoing",
    "passionate",
    "patient",
    "persistent",
    "playful",
    "positive",
    "powerful",
    "proud",
    "quick",
    "radiant",
    "reliable",
    "respectful",
    "risk-taking",
    "savvy",
    "sensible",
    "skillful",
    "smart",
    "sophisticated",
    "spontaneous",
    "strong",
    "supportive",
    "talented",
    "tenacious",
    "trustworthy"];

  const animals = [
    "aardvark",
    "antelope",
    "armadillo",
    "baboon",
    "barracuda",
    "bat",
    "bear",
    "beaver",
    "bison",
    "booby",
    "buffalo",
    "bulldog",
    "burro",
    "butterfly",
    "camel",
    "capybara",
    "cat",
    "caterpillar",
    "chameleon",
    "cheetah",
    "chimpanzee",
    "clownfish",
    "cobra",
    "cougar",
    "cow",
    "coyote",
    "crab",
    "crane",
    "crocodile",
    "deer",
    "dolphin",
    "donkey",
    "duck",
    "eagle",
    "elephant",
    "elk",
    "emu",
    "falcon",
    "ferret",
    "flamingo",
    "fox",
    "frog",
    "gazelle",
    "giraffe",
    "goat",
    "goose",
    "gorilla",
    "guinea pig",
    "hamster",
    "hawk",
    "hedgehog",
    "hippopotamus",
    "horse",
    "hummingbird",
    "hyena",
    "iguana",
    "impala"];

  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomAnimal = animals[Math.floor(Math.random() * animals.length)];

  return `${randomAdjective} ${randomAnimal} `;
}